In [ ]:
import pandas as pd
import numpy as np

In [24]:
data = pd.read_csv("../house_price_regression_dataset.csv")

In [25]:
df = data.copy()

In [26]:
df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [27]:
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [28]:
df.describe()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2815.422000,2.990000,1.973000,1986.550000,2.778087,1.022000,5.615000,6.188610e+05
std,1255.514921,1.427564,0.820332,20.632916,1.297903,0.814973,2.887059,2.535681e+05
min,503.000000,1.000000,1.000000,1950.000000,0.506058,0.000000,1.000000,1.116269e+05
25%,1749.500000,2.000000,1.000000,1969.000000,1.665946,0.000000,3.000000,4.016482e+05
50%,2862.500000,3.000000,2.000000,1986.000000,2.809740,1.000000,6.000000,6.282673e+05
75%,3849.500000,4.000000,3.000000,2004.250000,3.923317,2.000000,8.000000,8.271413e+05
max,4999.000000,5.000000,3.000000,2022.000000,4.989303,2.000000,10.000000,1.108237e+06

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [38]:
X = df.drop(columns = ["House_Price"])
y = df["House_Price"]

In [39]:
X.columns

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality'],
      dtype='str')

In [40]:
y

0      2.623829e+05
1      9.852609e+05
2      7.779774e+05
3      2.296989e+05
4      1.041741e+06
           ...
995    7.014940e+05
996    6.837232e+05
997    5.720240e+05
998    9.648653e+05
999    7.425993e+05
Name: House_Price, Length: 1000, dtype: float64

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
from sklearn.linear_model import LinearRegression

In [49]:
Pipeline_model = Pipeline(steps=[
    ("scaled" , StandardScaler()),
    ("model" , LinearRegression())
])

In [50]:
Pipeline_model.fit(X_train , y_train)

y_pred = Pipeline_model.predict(X_test)

In [51]:
from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error

In [52]:
re = r2_score(y_pred , y_test)
mae = mean_absolute_error(y_pred , y_test)
mse= mean_squared_error(y_pred , y_test)
mase = np.sqrt(mean_squared_error(y_pred , y_test))

In [53]:
print(f"r2_score  {re}")
print(f"mean_absoulute_error  {mae}")
print(f"mean_squared_error  {mse}")
print(f"mase  {mase}")

r2_score  0.9984045915312589
mean_absoulute_error  8174.583600006653
mean_squared_error  101434798.50563647
mase  10071.484424137112

In [54]:
import joblib
joblib.dump(Pipeline_model, "house_price_model.pkl")
print("Saved: house_price_model.pkl")

Saved: house_price_model.pkl